name: Export KPI Data to Google Drive

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9 AM UTC
  workflow_dispatch:

jobs:
  export-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install requests

      - name: Run export scripts
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
        run: |
          python .github/scripts/export_oc1.py
          python .github/scripts/export_oc4.py
          python .github/scripts/export_ot2.py
          python .github/scripts/export_ot3.py
          python .github/scripts/export_ot4.py

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone from base64
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF_B64 }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Upload KPI CSVs to Google Drive
        run: |
          rclone copyto OC1.csv gdrive:/APEC-RISE/OC1.csv
          rclone copyto OC4.csv gdrive:/APEC-RISE/OC4.csv
          rclone copyto OT2.csv gdrive:/APEC-RISE/OT2.csv
          rclone copyto OT3.csv gdrive:/APEC-RISE/OT3.csv
          rclone copyto OT4.csv gdrive:/APEC-RISE/OT4.csv

