name: Export KPI Data to Google Drive

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9 AM UTC
  workflow_dispatch:

jobs:
  export-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install requests

      - name: Run export scripts
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
        run: |
          python .github/scripts/export_oc1.py
          python .github/scripts/export_oc4.py
          python .github/scripts/export_ot4.py

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Upload CSVs to Google Drive
        run: |
          rclone copy OC1.csv gdrive:/APEC-RISE/
          rclone copy OC4.csv gdrive:/APEC-RISE/
          rclone copy OT4.csv gdrive:/APEC-RISE/
