name: Get Tableau Project IDs

on:
  workflow_dispatch:  # Manual trigger

jobs:
  get-project-id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Tableau Project Lookup Script
        env:
          TABLEAU_TOKEN_NAME: ${{ secrets.TABLEAU_TOKEN_NAME }}
          TABLEAU_TOKEN_SECRET: ${{ secrets.TABLEAU_TOKEN_SECRET }}
          TABLEAU_SITE_ID: ${{ secrets.TABLEAU_SITE_ID }}
        run: python .github/scripts/get_tableau_projects.py
