name: Publish Risk Signals to Tableau Cloud

on:
  push:
    paths:
      - 'data/risk_signals.csv'
      - '.github/scripts/publish_to_tableau.py'
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 AM UTC

jobs:
  publish-to-tableau:
    runs-on: ubuntu-latest

    env:
      TABLEAU_TOKEN_NAME: ${{ secrets.apec-risk-publisher }}
      TABLEAU_TOKEN_VALUE: ${{ secrets./NH9ScBsReG+HKbWMMoZ4Q==:zNkZHTry1XOQwj1nnI6PVH6AqX4pnxSV }}
      TABLEAU_SITE_ID: ${{ secrets.thecadmusgrouponline }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install pandas requests tableauhyperapi tableauserverclient

      - name: Run Tableau publishing script
        run: python .github/scripts/publish_to_tableau.py
