name: Publish Risk Signals to Tableau Cloud

on:
  # ✅ Run when relevant files are pushed
  push:
    branches:
      - main
    paths:
      - 'data/risk_signals.csv'
      - '.github/scripts/publish_to_tableau.py'

  # ✅ Run on manual trigger from Actions tab
  workflow_dispatch:

  # ✅ Run on schedule (every day at 6:00 AM UTC)
  schedule:
    - cron: '0 6 * * *'

jobs:
  publish-to-tableau:
    runs-on: ubuntu-latest

    env:
      TABLEAU_TOKEN_NAME: ${{ secrets.TABLEAU_TOKEN_NAME }}
      TABLEAU_TOKEN_VALUE: ${{ secrets.TABLEAU_TOKEN_VALUE }}
      TABLEAU_SITE_ID: ${{ secrets.TABLEAU_SITE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install pandas requests tableauhyperapi tableauserverclient

      - name: Run Tableau publishing script
        run: python .github/scripts/publish_to_tableau.py
